# Generated by Django 5.2.6 on 2025-09-18 01:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GitHub Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Twitter Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, numbers and underscores only.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')], verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last login'),
        ),
    ]
