# Generated by Django 5.2.6 on 2025-09-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
