# Generated by Django 5.2.6 on 2025-09-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='context_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
