# Generated by Django 5.2.6 on 2025-10-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emailverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='newsletter_subscription',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('login', 'Login Notification'), ('new_post', 'New Post Published'), ('new_comment', 'New Comment on Post'), ('new_like', 'Post Liked'), ('new_follower', 'New Follower'), ('password_reset', 'Password Reset'), ('account_update', 'Account Updated'), ('welcome', 'Welcome Email')], max_length=20),
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
