# Generated by Django 5.2.6 on 2025-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_newsletter_subscription_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['user', '-created_at'], name='users_email_user_id_ce7bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['notification_type', 'status'], name='users_email_notific_2c7716_idx'),
        ),
    ]
