# Generated by Django 5.2.6 on 2025-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_emailnotification_users_email_user_id_ce7bfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[('login', 'Login Notification'), ('new_post', 'New Post Published'), ('new_comment', 'New Comment on Post'), ('comment_reply', 'New Reply to Comment'), ('new_like', 'Post Liked'), ('new_follower', 'New Follower'), ('password_reset', 'Password Reset'), ('account_update', 'Account Updated'), ('welcome', 'Welcome Email')], max_length=20),
        ),
    ]
