# Generated by Django 5.2.6 on 2025-11-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_emailnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
