# Generated by Django 5.2.6 on 2025-11-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_emailverificationotp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
