# Generated by Django 5.2.6 on 2025-09-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_featured_image_remove_post_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scheduled_date',
        ),
    ]
