# Generated by Django 5.2.6 on 2025-10-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/', verbose_name='Featured Image'),
        ),
    ]
