# Generated by Django 5.2.6 on 2025-11-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
    ]
