# Generated by Django 5.2.6 on 2025-11-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPostReadTracking',
        ),
    ]
