# Generated by Django 5.2.6 on 2025-11-13 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_userpostreadtracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is Approved')),
                ('is_flagged', models.BooleanField(default=False, verbose_name='Is Flagged')),
                ('flagged_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Flagged Reason')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='Parent Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['post', '-published_date'], name='blog_commen_post_id_d50a8a_idx'), models.Index(fields=['author', '-published_date'], name='blog_commen_author__444bac_idx'), models.Index(fields=['is_approved', 'is_flagged'], name='blog_commen_is_appr_53c2a7_idx'), models.Index(fields=['parent'], name='blog_commen_parent__43ce68_idx')],
            },
        ),
    ]
