# Generated by Django 5.2.6 on 2025-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, editable=False, max_length=500, verbose_name='Summary'),
        ),
    ]
