# Generated by Django 5.2.6 on 2025-11-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_generated_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ai_generated_tags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='content_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='embeddings_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
